bookmark/urls.py
from django.urls import path
#from . import views ( views.list 이렇게 써야 함)
from .views import * #(list 이렇게 접근 가능함)

# 2차 url
app_name = 'bookmark'
# app_name 은 template 등에서 쉽게 접근하기 위해 사용한다. ex) bookmark:detail
urlpatterns=[
    #path('url pattern', view, name)
    # name은 name으로 url pattern을 찾는다.
    # 함수형 View 는 함수 이름만, Class View 는 ClassName.as_view()
    #path('', list, name='list'),
    path('', BookmarkListView.as_view(), name="list"),
    path('create/', BookmarkCreateView.as_view(), name='create'),
    # <1:2> 1: data type, 2: data name, 1번은 빠져도 되지만 2번은 빠지면 안된다.
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    # path 와 repath가 구분되어졌다.
    # repath(regexp, , ,) -> 정규표현식으로 쓰기 어려워지면서 나눠짐
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 1차에서 2차인 bookmark url로 토스
    # -> include('bookmark/urls')파일 경로
    # 1차 url 을 없앤다. -> ''
    # path('url pattern',view, name) 인데
    # view에서 include는 url 토스해주는 역할
    path('', include('bookmark.urls')),

    # bookmark.urls.list 를 기본 페이지로 만들겠다.
    # from bookmark.ulrs import *
    # path('',list)
]

bookmark/models.py
from django.db import models

# Create your models here.
# DB 에 직접 접근하는 것이 아니라 ORM 기능을 통해서 접근
# 모델은 class 로 만든다.

class Bookmark(models.Model):
    # 필드 : DB에 어떤 컬럼, 어떤 형태, 어떤 제약조건
    # 필드 목적 2: 프론트에서 Form tag에 어떤 제약조건을 할지 공통으로 생성
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    # Override -> java 에서 Object 객체의 toString
    # self -> java 에서 this
    def __str__(self):
        return self.site_name + " : " + self.url

    # inner class
    class Meta:
        # 해당 모델에 대한 옵션 값
        # 정렬, 출력될 모델 이름
        ordering = ['site_name']

        # ordering 은 정렬한다 '=..' 은 역순이다.

    # ToDo : get_absolute_url
    # 글쓰기, 수정하기 -> 완료되었습니다. 글 상세화면
    def get_absolute_url(self):
        from django.urls import reverse
        # return detail/3
        return reverse('bookmark:detail', args=[str(self.id)])

    """
    def some_func(a, *args, **kwargs):
        args 는 입력받는 인자의 개수를 모를 때 사용한다.
        kwargs 는 인자가 map일 때 사용된다.
    some_func(1,2,3,4,name='jake') 이면
        kwargs['name'] 으로 사용가능
    """

bookmark/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

# View 는 2종류가 있다. Function View 와 Class View
# 장고 목적: python 으로 web 구현하기 귀찮으니깐 편하게
# class 형: 자주 쓰는 기능을 상속받아서 간단하게 생성 -> 자주 사용한다.

# 오늘 하는 일은 기본 구현되어있는 View 들을 상속받아 사용
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

"""
def list(request):
    return HttpResponse('List Page')
"""
# ListView 상속
from .models import Bookmark

class BookmarkListView(ListView):
    model = Bookmark # Bookmark model 을 가져옴
    # 클래스형 View는 기본적으로 렌더링할 템플릿 파일이 지정이 되어있다.
    # bookmark/bookmark_list.html

"""
def write(request):
    return HttpResponse('Write Page')
"""
from django.urls import reverse_lazy
class BookmarkCreateView(CreateView):
    model = Bookmark # 입력화면에 출력된 form tag를 자동으로 만들어줌
    # _form : create , update
    # 원래 template 의 이름이 _form 인데 _create 로 변경
    template_name_suffix = '_create'
    # 입력받을 필드 목록
    fields = ['site_name', 'url']
    # success_url 이 없으면 model 에 get_absolute_url 이 실행
    success_url = reverse_lazy('list')


"""
def update(request):
    return HttpResponse('List Page')
"""
class BookmarkUpdateView(UpdateView):
    model = Bookmark
    template_name_suffix='_update'
    fields=['site_name', 'url']

"""
def delete(request):
    return HttpResponse('List Page')
"""
class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

class BookmarkDetailView(DetailView):
    model = Bookmark

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title%} Confirm Delete {% endblock %}
{% block content %}

<form action ="" method="post" >
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}" </div>
    <input type="submit" value="Delete" class="btn btn-danger"/>
</form>

{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %} Bookmark Write {% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        # 보안에서 꼭 필요, 장고에서 이 내용이 없으면 정상적으로 입력을 받지 않는다.
        # CSRF 공격에 대비
        {{ form.as_p }}
        # CreateView 에서 제공하는 것으로 자동으로 form 을 만들어 field 에 대한 form 을 만든다.
        # form 태그 목록으로 나온 것을 p 태그로 묶어준다는 의미
        <input type="submit" class="btn btn-success" value="Write">
    </form>

{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %} Bookmark Detail {% endblock %}

{% block content%}

<!-- detail에서는 1개의 데이터만 오므로 object를 사용한다. -->
{{object.site_name}} <br>
{{object.url}}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html'%}
{% block title %}Bookmark List {% endblock %}
<!-- Template 문법 -->

<!-- { % ... % } -> 기능 태그 - 닫는 태그 { % endtag % } -->
<!-- { { .... } } -> 출력 태그 -->
{% csrf_token %}
{% block content %}
<div class="btn-group d-block text-right mb-1" role="group">
  <a href="{% url 'bookmark:create' %}" class="btn btn-info">Add</a>
</div>

<table>
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Site</th>
          <th scope="col">URL</th>
          <th scope="col">Modify</th>
          <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
    {% for bookmark in object_list %}
    <!-- object_list 는 view 에서 받아 온 model 로 내부적으로 구현됨-->
    <!-- 하나일 때는 object 로 사용한다. -->
    <tr>
        <td>
            {{ forloop.counter }}
            <!-- forloop 는 현재 for 문에서 사용하는 기본 변수 -->
        </td>
        <td>
            <!-- URL Filter - 'bookmark namespace 안에 detail' < int,pk >를 맞춰줌 -->
            <a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.site_name }}</a>

        </td>
        <td>
            <a href="{{bookmark.url}}" target="_blank" class="btn btn-success">{{ bookmark.url }}</a>
            <!-- target="_blank" 는 새 창으로 띄운다. -->
            <!-- class 는 bootstrap 에 button 에서 가져옴 -->
        </td>
        <td>
            <a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-success btn-sm">modify</a>
        </td>
        <td>
            <a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %} Bookmark Update {% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        # 보안에서 꼭 필요, 장고에서 이 내용이 없으면 정상적으로 입력을 받지 않는다.
        # CSRF 공격에 대비
        {{ form.as_p }}
        # CreateView 에서 제공하는 것으로 자동으로 form 을 만들어 field 에 대한 form 을 만든다.
        # form 태그 목록으로 나온 것을 p 태그로 묶어준다는 의미
        <input type="submit" class="btn btn-success" value="update">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     {% load static %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
<!--
    공통된 영역 -> 글로벌 네비게이션, 사이드 메뉴, 카트, 로그인 등
                하위 템플릿에서 사용할 블록
-->
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">

          </div>
          <div class="col-4 text-center">
            <a class="header-logo text-dark" href="/">Bookmark</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>